Start HW_7
Rublov3110/HW_7 pull request #1
Opened 2022-05-18 19:52 UTC by Rublov3110

Start HW_7

2022-05-19 17:22 UTC, DmytroZhuravlov14 requested changes

2022-05-19 17:22 UTC, DmytroZhuravlov14 commented on Accessories/CoolingSystemAccessories.cs
> +        {
Since there is no logic of getting and setting this properties - u can make them automatic props instead

2022-05-19 17:22 UTC, DmytroZhuravlov14 commented on PC/HousingDerivative/PowerUnit.cs
> +            Console.WriteLine("Power unit:");
Every each of them doing kind of the same console output - make a separate method for such a logic

2022-05-20 19:25 UTC, merged

2022-05-20 19:26 UTC, Rublov3110 commented
HW_7_v2